package lexer;

public enum Tag {
    AND, ASSIGNMENT, ARRAY, BASIC, BAD_TOKEN, CB, CC, CHAR, COMMA, CONSTR, CP, DECR, DIV, ELSE, EOF, EQ, FALSE, FN, GE, GT, ID, IF, IMPL, INCR, INT, LE, LT, MINUS, MOD, MULT, NE, NEW, NIL, NOT, OB, OC, OP, OR, PLUS, PRIV, RET, RET_TYPE, SC, SELF, START, ST, STR, STRUCT, TRUE, WHILE;
}
