package lexer;

public enum Type {
    BAD_TOKEN, STRUCT_ID, BAD_STRUCT_ID, MEMBER_ID, INT_LITERAL, CHAR_LITERAL, BAD_CHAR_LITERAL, BAD_STR_LITERAL, STR_LITERAL, EOF, SCOPE, FN, IF, ELSE, STRUCT, IMPL, START, RET, NEW, BOOL_LITERAL, TYPE, ARRAY, NIL, DOT, COLON, COMMA, SEMICOLON, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, CLOSE_SQUARE_BRACKET, OPEN_SQUARE_BRACKET, OPEN_CURLY_BRACKET, CLOSE_CURLY_BRACKET, ASSIGNMENT, RETURN_TYPE, MULTIPLICATION, MODULO, DIVISION, EQUALS, NOT_EQUALS, DECREMENT, MINUS, INCREMENT, PLUS, AND, OR, NOT, LESS_THAN_OR_EQUALS, GRATER_THAN_OR_EQUALS, LESS_THAN, GREATER_THAN, WHILE;
}
